lynko/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html', form_class=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
]

lynko/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
   path('', views.index, name='index'), 
   path('about/', views.about, name='about'), 
   path('pricing/', views.pricing, name='pricing'), 
]

lynko/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

lynko/link/urls.py
from django.urls import path
from . import views

app_name = 'link'

urlpatterns = [
    path('categories/create-category/', views.create_category, name='create_category'),
    path('create-link/', views.create_link, name='create_link'),
    path('categories/', views.categories, name='categories'),
    path('categories/<int:pk>/edit/', views.edit_category, name='edit_category'),
    path('categories/<int:pk>/delete/', views.delete_category, name='delete_category'),
    path('<int:pk>/edit/', views.edit_link, name='edit_link'),
    path('<int:pk>/delete/', views.delete_link, name='delete_link'),
    path('', views.links, name='links'),
]

lynko/lynko/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('links/', include('link.urls')),
    path('dashboard/', include('dashboard.urls')),
]

lynko/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Plan(models.Model):
    name = models.CharField(max_length=255)
    max_num_links = models.IntegerField()

class User(AbstractUser):
    plan = models.ForeignKey(Plan, related_name='users', on_delete=models.CASCADE)

lynko/core/models.py
from django.db import models

# Create your models here.

lynko/dashboard/models.py
from django.db import models

# Create your models here.

lynko/link/models.py
from django.db import models
from accounts.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='categories', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering =('name',)
    
    def __str__(self):
        return self.name
    
class Link(models.Model):
    category = models.ForeignKey(Category, related_name='links', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    url = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='links', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('-created_at',)

lynko/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

lynko/link/forms.py
from django import forms
from .models import Category, Link

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
        
class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('category','name', 'description', 'url')

lynko/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from .models import User
from .forms import SignupForm
# Create your views here.




def signup(request):
    
    if request.method == "POST":
        
        form = SignupForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            authenticate(username=user.username, password=user.password)
            
            if user is not None:
                login(request, user)
                return redirect('/dashboard/')
    else:
        form = SignupForm()   
             
    return render(request, 'accounts/signup.html',{
        'form': form
    })

lynko/core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

def pricing(request):
    return render(request, 'core/pricing.html')

lynko/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from link.models import Link


@login_required
def dashboard(request):
    newest_links = Link.objects.filter(created_by=request.user)[0:5]
    return render(request, 'dashboard/dashboard.html', {
        'newest_links': newest_links
    })

lynko/link/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import CategoryForm, LinkForm
from .models import Category, Link




@login_required
def links(request):
    category = request.GET.get('category', '')
    
    links = Link.objects.filter(created_by = request.user)
    
    if category:
        links = links.filter(category_id=category)
    
    return render(request, 'link/links.html',{
        'links': links,
        'category': category,
    })
    

@login_required
def categories(request):
    categories = Category.objects.filter(created_by=request.user)
    
    return render(request, 'link/categories.html',{
        'categories': categories,
    })



@login_required
def create_link(request):
    
    if request.method == 'POST':
        form = LinkForm(request.POST)
        
        if form.is_valid():
            category = form.save(commit=False)
            category.created_by = request.user
            
            # print(f"User: {request.user}")
            
            category.save()
            
            return redirect('/dashboard/')
        
    else:
        form = LinkForm()
        form.fields['category'].queryset = Category.objects.filter(created_by=request.user)
    
    return render(request, 'link/create_link.html', {
        'form': form,
        'title': 'Create link',
    })

@login_required
def edit_link(request, pk):
    
    link = get_object_or_404(Link, created_by = request.user, pk=pk)
    
    if request.method == 'POST':
        form = LinkForm(request.POST, instance=link)
        
        if form.is_valid():
            form.save()
            
            return redirect('/links/')
        
    else:
        form = LinkForm(instance=link)
        form.fields['category'].queryset = Category.objects.filter(created_by=request.user)
    
    return render(request, 'link/create_link.html', {
        'form': form,
        'title': 'Edit link',
    })


@login_required
def delete_link(request, pk):
    
    link = get_object_or_404(Link, created_by = request.user, pk=pk)
    link.delete()
    return redirect('/links/')





@login_required
def create_category(request):
    
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        
        if form.is_valid():
            category = form.save(commit=False)
            category.created_by = request.user
            
            # print(f"User: {request.user}")
            
            category.save()
            
            return redirect('/dashboard/')
        
    else:
        form = CategoryForm()
    
    return render(request, 'link/create_category.html', {
        'form': form,
        'title': 'Create category',
    })


@login_required
def edit_category(request, pk):
    category = get_object_or_404(Category, created_by=request.user, pk=pk)
    
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        
        if form.is_valid():
            form.save()
            
            return redirect('/links/categories/')
    else:
        form = CategoryForm(instance=category)
    
    return render(request, 'link/create_category.html', {
        'form': form,
        'title': 'Edit category',
    })
    
    
@login_required
def delete_category(request, pk):
    category = get_object_or_404(Category, created_by=request.user, pk=pk)
    category.delete()
    
    return redirect('/links/categories/')

lynko/accounts/templates/accounts/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <h1 class="text-xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}
        <button class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Submit</button>
    </form>

{% endblock %}

lynko/accounts/templates/accounts/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <h1 class="text-xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}
        <button class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Submit</button>
    </form>

{% endblock %}

lynko/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <h1 class="text-xl">About Lynko</h1>
{% endblock %}

lynko/core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %}{% endblock %} | Lynko</title>
    </head>
    <body>
        <nav class="p-6 flex items-center justify-between bg-gray-800">
            <a href="/" class="text-xl text-cyan-500">Lynko</a>

            <div class="space-x-4">
                <a href="{% url 'core:about' %}" class="text-white">About</a>
                <a href="{% url 'core:pricing' %}" class="text-white">Pricing</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'link:links' %}" class="text-white">Links</a>
                    <!-- <a href="{% url 'accounts:logout' %}" class="py-4 px-6 bg-rose-600 text-white rounded-xl">Log out</a> -->
                    <a href="{% url 'dashboard:dashboard' %}" class="text-white">Dashboard</a>
                    <!-- <a href="{% url 'link:create_category' %}" class="py-4 px-6 bg-cyan-600 text-white rounded-xl">Create categoty</a> -->

                    <a href="{% url 'link:categories' %}" class="text-white">Categories</a>
                    <a href="{% url 'link:create_link' %}" class="py-4 px-6 bg-emerald-600 text-white rounded-xl">Create link</a>

                    <form method="POST" action="{% url 'accounts:logout' %}" class="inline">
                        {% csrf_token %}
                        <button type="submit" class="py-4 px-6 bg-rose-600 text-white rounded-xl">Log out</button>
                    </form>

                {% else %}
                    <a href="{% url 'accounts:signup' %}" class="py-4 px-6 bg-cyan-600 text-white rounded-xl">Sign up</a>
                    <a href="{% url 'accounts:login' %}" class="py-4 px-6 bg-gray-600 text-white rounded-xl">Log in</a>
                {% endif %}
            </div>
        </nav>

        <main class="p-6">
            {% block content %}

            {% endblock %}
        </main>

        <footer class="p-6 bg-gray-900">
            <p class="text-xs text-gray-400">Copyright (c) 2025 - Lynko</p>
        </footer>

    </body>
</html>

lynko/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1 class="text-xl">Welcome to Lynko</h1>
{% endblock %}

lynko/core/templates/core/pricing.html
{% extends 'core/base.html' %}

{% block title %}Pricing{% endblock %}

{% block content %}
    <h1 class="text-xl">Pricing</h1>
{% endblock %}

lynko/dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <h1 class="mb-6 text-xl">Dashboard</h1>

    <div class="p-6 bg-gray-100 rounded-xl">
        <h2 class="mb-4 text-xl">Newest links</h2>
        {% for link in newest_links %}
            <div class="mb-2 flex justify-between items-center">
                <p>{{ link.name }}</p>
                <a href="{{ link.url }}" class="underline" target="_blank">Open link</a>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

lynko/link/templates/link/categories.html
{% extends 'core/base.html' %}

{% block title %}Categories{% endblock %}

{% block content %}

    <h1 class="mb-6 text-xl">Categories</h1>

    <a href="{% url 'link:create_category' %}" class="inline-block mb-6 py-4 px-6 bg-cyan-600 text-white rounded-xl">Create categoty</a>

    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
            <div class="bg-gray-100 p-6 rounded-xl">
                <h2 class="mb-4 text-xl">{{ category.name }}</h2>

                <a href="{% url 'link:links' %}?category={{ category.id }}" class="text-cyan-700">View</a>
                |
                <a href="{% url 'link:edit_category' category.id %}" class="text-cyan-700">Edit</a>
                |
                <a href="{% url 'link:delete_category' category.id %}" class="text-cyan-700">Delete</a>

            </div>
        {% endfor %}

    </div>

{% endblock %}

lynko/link/templates/link/create_category.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="text-xl">{{ title }}</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}
        <button class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Submit</button>
    </form>

{% endblock %}

lynko/link/templates/link/create_link.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="text-xl">{{ title }}</h1>

    {% if request.user.links.all.count >= request.user.plan.max_num_links %}
        <div class="mt-6 p-6 bg-rose-600 text-white rounded-xl">
            You have reached the top of your plan!
        </div>
    {% else %}
        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}
            <button class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Submit</button>
        </form>
    {% endif %}
{% endblock %}

lynko/link/templates/link/links.html
{% extends 'core/base.html' %}

{% block title %}Links{% endblock %}

{% block content %}

    <h1 class="mb6 text-xl">Links</h1>

    <div class="mb-6 space-x-4 space-x-4" >
        {% for category in request.user.categories.all %}
            <a href="{% url 'link:links' %}?category={{ category.id }}">{{ category.name }}</a>
        {% endfor %}
    </div>

    <div class="grid grid-cols-3 gap-3">
        {% for link in links %}
            <div class="bg-gray-100 p-6 rounded-xl">
                <h2 class="mb-4 text-xl">{{ link.name }}</h2>

                {% if link.description %}
                    <p class="mb-4 text-xs">{{ link.description}}</p>
                {% endif%}

                <a href="{{ link.url }}" class="text-cyan-700" target="_blank">Open link</a>
                |
                <a href="{% url 'link:edit_link' link.id %}" class="text-cyan-700">Edit</a>
                |
                <a href="{% url 'link:delete_link' link.id %}" class="text-rose-700">Delete</a>
            </div>
           
        {% empty %}
            <div class="bg-rose-200 p-6 rounded-xl">
                You don't have any links for this filter..... please add some links first
            </div>
        {% endfor %}

    </div>

{% endblock %}